### ISSUE TITLE
1.124.2 - likely a typo in Aufrecht's line

### ISSUE THREAD

**Issue by WellRedPandit** [cceh/c-salt_vedaweb_tei#1]
Hello,

What you have both online and in rv_book_01.tei as Aufrecht's is this:

`áminatī daívyāni vratā́ni praminatī́ manuṣyāā̀ yugā́ni`

but in the book it is actually (and grammatically correct) this:

`áminatī daívyāni vratā́ni praminatī́ manuṣyā̀ yugā́ni`
 
Would you like me to submit a PR? or rather fix this typo yourself?

Thanks.

**Comment by dkwuerzburg** [comment]
Thanks for pointing this out. We will fix the typo.

**Comment by vocabulista** [comment]
Fixed with commit e1b1471826f021d29812ee81df4cf06f1f47017e
